### ISSUE TITLE
Initial round of review

### ISSUE THREAD

**Issue by ahmohamed** [DavisLaboratory/mastR#1]
Good work overall. The main problem is that you were checking on older R/Bioc versions, and so a lot of changes in the packages you're using were missed.

I've created a `develop` brach and deployed automated checks (R 4.2.2, current Bioc release). You can see the results in the "Actions" tab above.

Depending on the time you have available, we can work on prioritising the issues that we should fix and ones that we can leave for later.

@bhuvad @ningbioinfo I know you've had a look at the package already, so feel free to comment if you disagree with any of the issues below.

 - VERY IMPORTANT: Always run checks on the recent R / Bioc version.
 - SE and Suerat are used in method definition. They are a core part of you package and should be in `Imports`, not `Suggests`.
 - datasets should be loaded with `data(xx)` before being used.
 - `plot=TRUE` as a parameter is not a good design. Implement plotting functions separately.
 - In vignettes and examples, ideally, you should not download anything from internet. This takes times and results in flaky checks (will fail each time it has a bad connection).
 - Avoid pipes unless necessary inside your package code. 
 - If you're using pipes in your examples / vignette, they should be in top-level code only, not nested. This is both difficult to read and hard to debug. (Vignette L:142)
 - Avoid unnecessary chaining in your examples (Vignette L:179)
 - Stay consistent in your variable names, should not start with a capital letter.
 - Why `org.Hs.eg.db` is in `Depends`?
 - The example in (Vignette L:289) is completely not suitable for demo. `CCLE` has 27M rows. This is crazy!!
 - `filter_non_tissue` is unclear why it's names like that, or it's function. It looks like a subsetter for CCLE. 
 - Generic functions should re-use the code where possible. For example, convert input to matrix and then call `method.matrix(...)`.
 - Don't use the same variable name multiple times inside the same function (see `gsea_plot_init`).
 - `sig_gseaplot` is broken in 4.2.2 / Bioc 3.16.
 - `dplyr::arrange_` is deprecated along time ago. Use `dplyr::arrange` and quosures instead.

**Comment by Gene233** [comment]
Hi @ahmohamed Thank you very much for help me check it!

* For SE and Seurat object, because the 2 class is for scRNA object, which is an additional class as input. So I didn't import them as to reduce the numer of import packages... But if it's necessary, I'll add them in and see if there're any other packages I can remove.
* I'll add data("im_data_6") before using it in my example and test and vignette.
* I use `plot = TRUE` instead of plot separately because some of plots are implemented by limma functions, and limma use a plot = TRUE to add plots during model fitting, I don't want to rerun the whole model fit just for plotting. So I inherit it from limma, using plot = TRUE to control if to make plots before and after filtration and voom fitting.
* In the vignette I'll change to use only im_data_6 instead of DICE, but msigdb always requires to download or load msigdb database online, so might not be able to avoid? @bhuvad 
* I used pipes a lot as I tried to reduce intermediate variales and objects, but if it decreases the readibility of codes, I'll change some of them.
* yes, I'll modify vignette to avoid the chaining.
* I used `ID` as a param name because I think ID is more informative than id. But if it's not allowed I'll change it to id.
* I add `org.Hs.eg.db` in `depends` instead of `imports` because I used select function to convert input gene names into symbols, which requires `org.Hs.eg.db`. And `import` won't help library it. I'm not sure if it can work to import it at top of R script and move it to `Import`.
* As CCLE is the default setting in my package to filter genes not expressed by cancer cell lines, so I use CCLE as a demo, not sure if there's any better and smaller dataset for the same purpose?
* I used setGeneric and setMethod to re-use the codes, for most of the generic functions, I just convert them into one basic class (e.g. DGEList), and run with that function. Some times I kept Matrix and matrix in case users want to apply scRNA object, such as sce or seurat, then convert a sparse matrix (Matrix) to dense matrix would take time and memory to save larger object. So I kept Matrix and use Matrix::function to do the same process to the sparse matrix instead of converting Matrix to matrix.
* I'll check sig_gseaplot later. But not sure if it's possible to test it on server? I think the latest version in our server is R4.2.1. Is it the only way to test it on my local PC?
* `arrange `is the same issue as se and seurat, I try to reduce the number of import packages so not import rlang. Is rlang a basic package which don't need to worry about this?

Thank you very much for your comments. I'll fix those you mentioned first. And leave some I think might be better to fix later.
I'll catch-up with you next Monday!
